SchoolWebsite/Models/Specie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
/*
    * Model class Specie
    * Relations:
    *  Many to many: *
    *  One to many: Przedmiot(Each Specie can have many Products)
    */ 
namespace SchoolWebsite.Models
{
    public class Specie
    {
        public Specie()
        {
            Przedmioty = new List<Przedmiot>();
        }
        public int SpecieID { get; set; }
        [Required(ErrorMessage="Name is required")]
        [StringLength(20, ErrorMessage = "Maximum length 20")]
        public string Name { get; set; }

        public int PrzedmiotID { get; set; }
        public virtual ICollection<Przedmiot> Przedmioty { get; set; }

    }
}

SchoolWebsite/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolWebsite.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        // GET: Admin
        
        public ActionResult Index()
        {
            return View();
        }
    }
}

SchoolWebsite/Controllers/SpecieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolWebsite.Models;

namespace SchoolWebsite.Controllers
{
    [Authorize(Roles = "admin")]
    public class SpecieController : Controller
    {
        private readonly Context ctx = new Context();
        private readonly IRepository<Specie> repoSpecie;
        public SpecieController()
        {
            repoSpecie = new RepositoryT<Specie>(ctx);
        }
        // GET: Specie
       
        public ActionResult Index()
        {
            return View(repoSpecie.GetAll());
        }
        // Get specie/create
   

        public ActionResult Create()
        {
            return View();
        }
        //post specie/create
   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="SpecieID,Name")] Specie specie)
        {
            if (ModelState.IsValid)
            {
                repoSpecie.Add(specie);
                return RedirectToAction("Index");
            }

            return View(specie);
        }
        //get specie/edit
  
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var specie = repoSpecie.Get(id);
            if (specie == null)
            {
                return HttpNotFound();
            }
            return View(specie);
        }
        //post specie/edit
    
        [HttpPost]
         [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SpecieID,Name")]Specie sp)
         {
             if(ModelState.IsValid){
                 repoSpecie.Edit(sp,sp.SpecieID);
                 return RedirectToAction("Index");
             }
             return View(sp);
         }

        //get specie/delete
   
        public ActionResult Delete(int id)
        {

            return View(repoSpecie.Get(id));
       
        }

        //post specie/delete
  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id )
        {
            if (id == null)
                return HttpNotFound();
            else
            {
                Specie sp = repoSpecie.Get(id);
                repoSpecie.Delete(sp);
               return RedirectToAction("Index");
                
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoSpecie.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolWebsite/Views/Specie/Create.cshtml
@model SchoolWebsite.Models.Specie
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm()) { 
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m=> m.Name)
            @Html.EditorFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name,"", new {@class ="text-danger" })
        </div>
    </div>
    <input type="submit"value="Create" class="btn btn-default"/>
    @Html.ActionLink("Back to List", "Index")
}

SchoolWebsite/Views/Specie/Delete.cshtml
@model SchoolWebsite.Models.Specie
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Are you sure u want to delete this</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(m=> m.Name)
    </dt>
    <dd>
        @Html.DisplayFor(m=> m.Name)
    </dd>
</dl>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <input type="submit" value="Delete" class="btn btn-default" />
        @Html.ActionLink("Back to List", "Index")
     </div>
}

SchoolWebsite/Views/Specie/Edit.cshtml
@model SchoolWebsite.Models.Specie
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Edit</h2>
<div class="col-lg-6">
    <p> Current data</p>
    <dl>
        <dt>
            @Html.DisplayNameFor(m => m.Name)
        </dt>
        <dd>
            @Html.DisplayFor(m=>m.Name)
        </dd>
    </dl>
    <p class="pull-left">@Html.ActionLink("Go back to list", "Index")</p>
</div>

<div class="col-lg-6">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.SpecieID)
        <div class="form-horizontal">
            @Html.LabelFor(m=>m.Name)
            @Html.EditorFor(m=>m.Name)
            @Html.ValidationMessageFor(m=>m.Name)
        </div>
        <br />
        <input type="submit" value="Change data" class="btn btn-default" />
    }
</div>

SchoolWebsite/Views/Specie/Index.cshtml
@model IQueryable<SchoolWebsite.Models.Specie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Species</h2>
<p>
@Html.ActionLink("Create new", "Create", "Specie")
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m=>m.FirstOrDefault().Name)
        </th>
    </tr>
    @foreach (var specie in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(m => specie.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = specie.SpecieID })
                @Html.ActionLink("Delete", "Delete", new { id = specie.SpecieID })
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Admin page", "Index", "Admin")